@url = http://localhost:3615

### BASE
{{url}}

### ALL EMPLOYEES
{{url}}/employees

### ADD EMPLOYEE
POST {{url}}/employee
content-type: application/json
 
{
    "lastName": "Abdulrazak",
    "firstName": "Abdul",
    "title": "Sales Representative",
    "notes": "Abdulrazak is a test employee that we are adding."
}
### DELETE Employee
DELETE {{url}}/employee/63f23a79d548dbfecea2680e

### EDIT EMPLOYEE 
PATCH {{url}}/employee/63f2370dcd59b592a6201373
content-type: application/json

{
"lastName": "CHANGED-LAST-NAME1", "firstName": "CHANGED-FIRST-NAME1", "title": "Sales Representative", "notes": "Author is a test employee that we are adding."
}